### ISSUE TITLE
Duckdb version is too constrained

### ISSUE THREAD

**Issue by ADBond** [conda-forge/splink-feedstock#43]
### Comment:

Can't use newer duckdb releases, excluding the use of e.g. `damerau_levenshtein`. Other dependencies may similarly be overly constrained currently.

See [this comment](https://github.com/moj-analytical-services/splink/issues/1311#issuecomment-1611426867).

**Comment by ADBond** [comment]
@espenfl I have updated the build for the latest version of Splink (3.9.2) in #44 - I have tested the build out, and appears to be working okay (with duckdb 0.8.1 installed), but do let me know if you try this out and run into any issue.

**Comment by espenfl** [comment]
@ADBond Excellent. Thanks a lot. Will try it right away and report back.

**Comment by espenfl** [comment]
@ADBond Yes. This looks fine now. Tutorial runs out of the box with the update. Thanks.

**Comment by ADBond** [comment]
> @ADBond Yes. This looks fine now. Tutorial runs out of the box with the update. Thanks.

Great! Will try to keep things more up-to-date going forward, but don't hesitate to reach out again if you run into issues down the line.
